spring:
  config:
    import: optional:file:./workload-service/.env[.properties]
  application:
    name: workload-service
  data:
    mongodb:
      uri: mongodb://gym:gym@localhost:27017/workloaddb?authSource=admin
  activemq:
    broker-url: tcp://localhost:61616
    user: gca
    password: gca
    pool:
      enabled: false

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

workload:
  queue:
    name: trainer.workload.queue
  dlq:
    name: ActiveMQ.DLQ

jms:
  request-timeout-ms: 5000