spring:
  application:
    name: workload-service
  datasource:
    url: jdbc:h2:mem:workloaddb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: gym
    password: gym
  h2:
    console:
      enabled: true

server:
  port: 8082

jwt:
  secret: gym-crm-secret-key-1234567890XXABCD

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/