spring:
  config:
    import: optional:file:./workload-service/.env[.properties]
  application:
    name: workload-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/workloaddb?authSource=admin
  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:${ACTIVEMQ_PORT}
    user: ${ACTIVEMQ_USER}
    password: ${ACTIVEMQ_PASSWORD}
    pool:
      enabled: false

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/

workload:
  queue:
    name: trainer.workload.queue
  dlq:
    name: ActiveMQ.DLQ

jms:
  request-timeout-ms: 5000