spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  activemq:
    broker-url: ${JMS_BROKER_URL}
    user: ${JMS_USER}
    password: ${JMS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.gcs.app: INFO