spring:
  datasource:
    url: jdbc:h2:mem:gym_test_db;DB_CLOSE_DELAY=-1
    username: sa
    driver-class-name: org.h2.Driver

  activemq:
    broker-url: tcp://activemq:61616

eureka:
  client:
    enabled: false

jwt:
  secret: ${JWT_TEST_SECRET}