spring:
  config:
    import: optional:file:./gateway-service/.env[.properties]
  application:
    name: gateway-service

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO

gateway:
  routes:
    - id: gca-core
      path: /gym-crm-core/api/**
      service-id: gca-core-service
      add-request-headers:
        X-From-Gateway: gateway-service
    - id: workload
      path: /api/workload/**
      service-id: workload-service
      add-request-headers:
        X-From-Gateway: gateway-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
    instances:
      gca-core-service:
        baseConfig: default
      workload-service:
        baseConfig: default